server:
  port: 9091
  application:
    name: restapicomponentone
# To allow all the actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "always"

#specific to spring-data-couchbase -- check in maven
spring:
  couchbase:
    connection-string: localhost
    username: StockService
    password: St0ckS3rv1c3
  data:
    couchbase:
      bucket-name: StockService